name: "Build"

on:
  push: 
    branches: [master, main]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm cache clean --force
      - run: npm ci
      - run: npm run build
